---
- name: Create container
  hosts: localhost
  gather_facts: no
  remote_user: root
  tasks:
    - name: rstudio container
      docker_container:
        name: rstudio-server
        image: studio
        state: started
        published_ports:
          - "8787:8787"
        tty: true
        detach: true
        env:
          PASSWORD: Passw0rd1
